services:
  deb:
    image: 'debian:stable'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - type: bind
        source: C:/models
        target: /models
      - type: bind
        source: './'
        target: /stt